services:
  nextjs-app:
    image: nextjs-app
    pull_policy: never
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: src/
          target: /app/src
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: package.json
        - action: restart
          path: .env

  postgres:
    image: postgres:18.2-alpine
    container_name: nextjs-app-db
    restart: always
    shm_size: 128mb
    volumes: 
      - postgres-data:/data/db
    env_file:
      - .env

volumes:
  postgres-data: